services:
  kademlianodes:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 50
      # restart_policy:
      #   condition: on-failure
      #   delay: 5s
      #   max_attempts: 3
      #   window: 10s
    networks:
      - kademlia_network
    environment:
      - PORT
      - BUCKET_SIZE
      - API_PORT
      - NODES_PROXY_DOMAIN
      - ALPHA
      - RPC_TIMEOUT_IN_SECONDS
      - DEBUG=true

networks:
  kademlia_network:
