// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: proto/kademlia.proto

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefreshTTLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key            string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	RequestingNode *Node  `protobuf:"bytes,2,opt,name=RequestingNode,proto3" json:"RequestingNode,omitempty"`
}

func (x *RefreshTTLRequest) Reset() {
	*x = RefreshTTLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kademlia_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshTTLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTTLRequest) ProtoMessage() {}

func (x *RefreshTTLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kademlia_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTTLRequest.ProtoReflect.Descriptor instead.
func (*RefreshTTLRequest) Descriptor() ([]byte, []int) {
	return file_proto_kademlia_proto_rawDescGZIP(), []int{0}
}

func (x *RefreshTTLRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RefreshTTLRequest) GetRequestingNode() *Node {
	if x != nil {
		return x.RequestingNode
	}
	return nil
}

type StoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key            []byte `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value          string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	RequestingNode *Node  `protobuf:"bytes,3,opt,name=RequestingNode,proto3" json:"RequestingNode,omitempty"`
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kademlia_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kademlia_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_kademlia_proto_rawDescGZIP(), []int{1}
}

func (x *StoreRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StoreRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StoreRequest) GetRequestingNode() *Node {
	if x != nil {
		return x.RequestingNode
	}
	return nil
}

type FindValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash           []byte `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	RequestingNode *Node  `protobuf:"bytes,2,opt,name=RequestingNode,proto3" json:"RequestingNode,omitempty"`
}

func (x *FindValueRequest) Reset() {
	*x = FindValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kademlia_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindValueRequest) ProtoMessage() {}

func (x *FindValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kademlia_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindValueRequest.ProtoReflect.Descriptor instead.
func (*FindValueRequest) Descriptor() ([]byte, []int) {
	return file_proto_kademlia_proto_rawDescGZIP(), []int{2}
}

func (x *FindValueRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *FindValueRequest) GetRequestingNode() *Node {
	if x != nil {
		return x.RequestingNode
	}
	return nil
}

type FindNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetID       []byte `protobuf:"bytes,1,opt,name=TargetID,proto3" json:"TargetID,omitempty"`
	RequestingNode *Node  `protobuf:"bytes,2,opt,name=RequestingNode,proto3" json:"RequestingNode,omitempty"`
}

func (x *FindNodeRequest) Reset() {
	*x = FindNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kademlia_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNodeRequest) ProtoMessage() {}

func (x *FindNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kademlia_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNodeRequest.ProtoReflect.Descriptor instead.
func (*FindNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_kademlia_proto_rawDescGZIP(), []int{3}
}

func (x *FindNodeRequest) GetTargetID() []byte {
	if x != nil {
		return x.TargetID
	}
	return nil
}

func (x *FindNodeRequest) GetRequestingNode() *Node {
	if x != nil {
		return x.RequestingNode
	}
	return nil
}

type StoreResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *StoreResult) Reset() {
	*x = StoreResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kademlia_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResult) ProtoMessage() {}

func (x *StoreResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kademlia_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResult.ProtoReflect.Descriptor instead.
func (*StoreResult) Descriptor() ([]byte, []int) {
	return file_proto_kademlia_proto_rawDescGZIP(), []int{4}
}

func (x *StoreResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         []byte `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IPWithPort string `protobuf:"bytes,2,opt,name=IPWithPort,proto3" json:"IPWithPort,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kademlia_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kademlia_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_proto_kademlia_proto_rawDescGZIP(), []int{5}
}

func (x *Node) GetID() []byte {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *Node) GetIPWithPort() string {
	if x != nil {
		return x.IPWithPort
	}
	return ""
}

type FindNodeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*Node `protobuf:"bytes,1,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
}

func (x *FindNodeResult) Reset() {
	*x = FindNodeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kademlia_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindNodeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNodeResult) ProtoMessage() {}

func (x *FindNodeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kademlia_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNodeResult.ProtoReflect.Descriptor instead.
func (*FindNodeResult) Descriptor() ([]byte, []int) {
	return file_proto_kademlia_proto_rawDescGZIP(), []int{6}
}

func (x *FindNodeResult) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type FindValueResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*FindValueResult_Nodes
	//	*FindValueResult_Data
	Value isFindValueResult_Value `protobuf_oneof:"Value"`
}

func (x *FindValueResult) Reset() {
	*x = FindValueResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kademlia_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindValueResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindValueResult) ProtoMessage() {}

func (x *FindValueResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kademlia_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindValueResult.ProtoReflect.Descriptor instead.
func (*FindValueResult) Descriptor() ([]byte, []int) {
	return file_proto_kademlia_proto_rawDescGZIP(), []int{7}
}

func (m *FindValueResult) GetValue() isFindValueResult_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *FindValueResult) GetNodes() *FindNodeResult {
	if x, ok := x.GetValue().(*FindValueResult_Nodes); ok {
		return x.Nodes
	}
	return nil
}

func (x *FindValueResult) GetData() string {
	if x, ok := x.GetValue().(*FindValueResult_Data); ok {
		return x.Data
	}
	return ""
}

type isFindValueResult_Value interface {
	isFindValueResult_Value()
}

type FindValueResult_Nodes struct {
	Nodes *FindNodeResult `protobuf:"bytes,1,opt,name=Nodes,proto3,oneof"`
}

type FindValueResult_Data struct {
	Data string `protobuf:"bytes,2,opt,name=Data,proto3,oneof"`
}

func (*FindValueResult_Nodes) isFindValueResult_Value() {}

func (*FindValueResult_Data) isFindValueResult_Value() {}

var File_proto_kademlia_proto protoreflect.FileDescriptor

var file_proto_kademlia_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x11, 0x52, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x54, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65,
	0x79, 0x12, 0x33, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4e,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x6b, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x33,
	0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4e,
	0x6f, 0x64, 0x65, 0x22, 0x5b, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x33, 0x0a, 0x0e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65,
	0x22, 0x62, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x44, 0x12,
	0x33, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x4e, 0x6f, 0x64, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x36, 0x0a,
	0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x50, 0x57, 0x69, 0x74, 0x68, 0x50,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x49, 0x50, 0x57, 0x69, 0x74,
	0x68, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x33, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x5f, 0x0a, 0x0f, 0x46, 0x69,
	0x6e, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2d, 0x0a,
	0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x42, 0x07, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xa1, 0x02, 0x0a, 0x08,
	0x4b, 0x61, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x12, 0x22, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67,
	0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x1a, 0x0b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x08,
	0x46, 0x69, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x46, 0x69, 0x6e,
	0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x05, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x40, 0x0a,
	0x0a, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x54, 0x4c, 0x12, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x54, 0x4c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42,
	0x16, 0x5a, 0x14, 0x64, 0x37, 0x30, 0x32, 0x34, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x30,
	0x34, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_kademlia_proto_rawDescOnce sync.Once
	file_proto_kademlia_proto_rawDescData = file_proto_kademlia_proto_rawDesc
)

func file_proto_kademlia_proto_rawDescGZIP() []byte {
	file_proto_kademlia_proto_rawDescOnce.Do(func() {
		file_proto_kademlia_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_kademlia_proto_rawDescData)
	})
	return file_proto_kademlia_proto_rawDescData
}

var file_proto_kademlia_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_kademlia_proto_goTypes = []any{
	(*RefreshTTLRequest)(nil), // 0: proto.RefreshTTLRequest
	(*StoreRequest)(nil),      // 1: proto.StoreRequest
	(*FindValueRequest)(nil),  // 2: proto.FindValueRequest
	(*FindNodeRequest)(nil),   // 3: proto.FindNodeRequest
	(*StoreResult)(nil),       // 4: proto.StoreResult
	(*Node)(nil),              // 5: proto.Node
	(*FindNodeResult)(nil),    // 6: proto.FindNodeResult
	(*FindValueResult)(nil),   // 7: proto.FindValueResult
	(*empty.Empty)(nil),       // 8: google.protobuf.Empty
}
var file_proto_kademlia_proto_depIdxs = []int32{
	5,  // 0: proto.RefreshTTLRequest.RequestingNode:type_name -> proto.Node
	5,  // 1: proto.StoreRequest.RequestingNode:type_name -> proto.Node
	5,  // 2: proto.FindValueRequest.RequestingNode:type_name -> proto.Node
	5,  // 3: proto.FindNodeRequest.RequestingNode:type_name -> proto.Node
	5,  // 4: proto.FindNodeResult.Nodes:type_name -> proto.Node
	6,  // 5: proto.FindValueResult.Nodes:type_name -> proto.FindNodeResult
	5,  // 6: proto.Kademlia.Ping:input_type -> proto.Node
	3,  // 7: proto.Kademlia.FindNode:input_type -> proto.FindNodeRequest
	2,  // 8: proto.Kademlia.FindValue:input_type -> proto.FindValueRequest
	1,  // 9: proto.Kademlia.Store:input_type -> proto.StoreRequest
	0,  // 10: proto.Kademlia.RefreshTTL:input_type -> proto.RefreshTTLRequest
	5,  // 11: proto.Kademlia.Ping:output_type -> proto.Node
	6,  // 12: proto.Kademlia.FindNode:output_type -> proto.FindNodeResult
	7,  // 13: proto.Kademlia.FindValue:output_type -> proto.FindValueResult
	4,  // 14: proto.Kademlia.Store:output_type -> proto.StoreResult
	8,  // 15: proto.Kademlia.RefreshTTL:output_type -> google.protobuf.Empty
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_kademlia_proto_init() }
func file_proto_kademlia_proto_init() {
	if File_proto_kademlia_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_kademlia_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RefreshTTLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kademlia_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*StoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kademlia_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*FindValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kademlia_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*FindNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kademlia_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*StoreResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kademlia_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kademlia_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*FindNodeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kademlia_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*FindValueResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_kademlia_proto_msgTypes[7].OneofWrappers = []any{
		(*FindValueResult_Nodes)(nil),
		(*FindValueResult_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_kademlia_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kademlia_proto_goTypes,
		DependencyIndexes: file_proto_kademlia_proto_depIdxs,
		MessageInfos:      file_proto_kademlia_proto_msgTypes,
	}.Build()
	File_proto_kademlia_proto = out.File
	file_proto_kademlia_proto_rawDesc = nil
	file_proto_kademlia_proto_goTypes = nil
	file_proto_kademlia_proto_depIdxs = nil
}
